### ISSUE TITLE
The "no-image" image should not be white

### ISSUE THREAD

**Issue by blhough** [SRJC-Computer-Science-Club/CS-Website#47]
The project names are white so it does not show up when overlaid.

**Comment by LinnierGames** [comment]
I was thinking of giving the project title a black shadow, like a small small enough one to read the title, maybe?

**Comment by blhough** [comment]
sure but you could also make a more pleasing looking "no-image"

**Comment by LinnierGames** [comment]
True, true. I need to be thinking more about guests viewing this site vs just members, thanks 👍
